  version: '3.5'

  services:
    db:
      container_name: pg_db
      image: postgres:14-alpine
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=admin
        - POSTGRES_DB=ypstorage
      ports:
        - "5432:5432"

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: sergeyavdeyy@gmail.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"

    minio:
      image: minio/minio
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - minio_storage:/data
      environment:
        MINIO_ROOT_USER: admin
        MINIO_ROOT_PASSWORD: strongpassword
      command: server --console-address ":9001" /data

  volumes:
    minio_storage: {}